{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.clusterRoleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRoleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.svcAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end }}